name: Deploy app (Functions + SWA)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  FUNCTION_APP_NAME: ${{ vars.FUNCTION_APP_NAME }}
  SWA_NAME: ${{ vars.SWA_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Deploy Azure Functions (Python)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: '.'

      - name: Deploy Static Web App (admin)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az extension add --name staticwebapp --yes || true
            az staticwebapp upload \
              --name $SWA_NAME \
              --source ./admin \
              --no-use-app-build-service true